### ISSUE TITLE
Change post linked to locale in another action execution

### ISSUE THREAD

**Issue by joeljv91** [lloc/Multisite-Language-Switcher#102]
Hi.

This plugin works really well, we are integrating a post duplicator with MSLS and my question is: There is a easy way to change linked post for one locale when we are in another action?

For example:

Site 1

Post 1200
msls_input_en_US => 123 <-- change this by other existing post (125) in site 2

I tried changing metas in original post but doesn't seems to work.

Thanks.

**Comment by lloc** [comment]
Did you had the chance to test the new Content Importer that comes with the plugin?
