### ISSUE TITLE
Really Simple SSL Integration

### ISSUE THREAD

**Issue by peterbisset** [lloc/Multisite-Language-Switcher#103]
I have recently upgraded one of my multisite domains to SSL and everything works fine except the links to the other sites in my network through the Multisite Language Switcher are now all https:// as well. The problem is the other sites are on http:// rather than https:// and therefore the links don’t work. On all of the other http:// sites the links work fine it’s just on the https:// site they point to the wrong url.

**Comment by lloc** [comment]
I believe that was something were a refresh of permalinks helps.
