### ISSUE TITLE
filter returns en_GB instead of en-gb

### ISSUE THREAD

**Issue by AtulDabhi** [lloc/Multisite-Language-Switcher#120]
I used below code to set hreflang value to specific one.

I used below code but it returns 'en_GB' instead of 'en-gb' as hreflang value.

`function my_msls_head_hreflang( $language ) {
    if ( 'en' == $language ) {
        $language = 'en-gb';
    }
    return $language;
}
add_filter( 'msls_head_hreflang', 'my_msls_head_hreflang' ); `

**Comment by lloc** [comment]
You can try something like this:

```function my_msls_head_hreflang( $language ) { 
    return 'en_GB' == $language ? 'en-gb' : $language;
}
add_filter( 'msls_head_hreflang', 'my_msls_head_hreflang' );```
