### ISSUE TITLE
Manipulate the Navigation Menu Snippet Parse Error

### ISSUE THREAD

**Issue by edwinbradford** [lloc/Multisite-Language-Switcher#123]
I've been using your simplified version of MslsMenu for a few months with no issues. I just updated and it generated a fatal PHP error. I found your [support site](https://realloc.gitbook.io/multisite-language-switcher/api/snippets-and-examples) and replaced the old version with your latest example: 

````
function my_custom_menu_item( $items, $args ) {
    if ( function_exists ( 'the_msls' ) && 'primary' == $args->theme_location ) {
        $obj = new lloc\Msls\MslsOutput::init();
        $arr = $obj->get( 1 );
        if ( !empty( $arr ) ) {
            $items .= '<li>' . implode( '</li><li>', $arr ) . '</li>';
        }
    }
    return $items;
}
add_filter( 'wp_nav_menu_items', 'my_custom_menu_item', 10, 2 );
````
That generates the following error:

`Parse error: syntax error, unexpected 'init' (T_STRING), expecting variable (T_VARIABLE) or '$' on line 19`

Where line 19 is the line that reads `$obj = new lloc\Msls\MslsOutput::init();`

Your MslsMenu plugin works without errors so it looks like the example above taken from your site doesn't function correctly.

I can simply use your MslsMenu plugin instead but I don't need the Admin features and your simplified version was super nice.

Thanks for such a great product by the way.

**Comment by lloc** [comment]
Yes, the documentation is somewhat behind ... sorry for that. I'm working on the documentation:

https://realloc.gitbook.io/multisite-language-switcher/

_I updated also msls.co with that info._

**Comment by edwinbradford** [comment]
Still getting the parse error above although absolutely everything else is working. I don't know how to bugfix it so I'm using the msls-menu plugin instead and customizing the output with the following in my functions.php:

````
// Customize MSLS HTML output
if ( function_exists ( 'the_msls' ) ) {
  function my_msls_output_get( $url, $link ) {
      return sprintf(
          '<li><a href="%s" alt="%s"><div></div><p>%s</p></a></li>',
          $url,
          $link->txt,
          $link
      );
  }
  add_filter( 'msls_output_get', 'my_msls_output_get', 10, 2 );
}
````
That's enough for me to upgrade.

**Comment by lloc** [comment]
I updated the documentation and corrected the above code: 

http://msls.co/developer-docs/snippets-examples.html#manipulate-the-nav-menu
