### ISSUE TITLE
Fatal error -- Plugin could not be activated

### ISSUE THREAD

**Issue by edwinbradford** [lloc/Multisite-Language-Switcher#124]
I have identical Wordpress 5.0.1 installations with the same database and the same theme both locally on my PC and on a remote site.

When upgrading MLS (Multi Language Switcher) from v.1.1 to v.2.0.3 there are no errors on my local installation but on attempting to activate the plugin on the remote site I get an error message stating activation failed.

`Parse error: syntax error, unexpected '[' in /pathToFile/MultisiteLanguageSwitcher.php on line 61`

As the installations are identical could this be connected to the PHP version? My local site is running PHP version 7.2.2 and the remote site is running PHP version 7.2.7.

As a side note on upgrading from MLS v.1.1 to v.2.0.3 the following MLS related functions broke. I was able to get the local installation of MLS working again by removing both functions below and using other solutions but I had to roll back the remote site to MLS v.1.1. 

The following broke on this line `$obj = new MslsOutput;`:

````
function mls_language_menu( $items, $args ) {
    if ( function_exists ( 'the_msls' ) && 'primary' == $args->theme_location ) {
        $obj = new MslsOutput;
        $arr = $obj->get( 1 ); // Where 1 is a preset for language name as text only
        if ( !empty( $arr ) ) {
            $items .= '<li>' . implode( '</li><li>', $arr ) . '</li>';
        }
    }
    return $items;
}
add_filter( 'wp_nav_menu_items', 'mls_language_menu', 10, 2 );

````

...and the following broke on this line `class MyMslsLink extends MslsLink {`

````
if ( function_exists ( 'the_msls' ) ) {
  function my_msls_link_create( $display ) {
  	class MyMslsLink extends MslsLink {
  		protected $format_string = '<div></div><p>{txt}</p>';
  	}
  	return new MyMslsLink;
  }
  add_filter( 'msls_link_create', 'my_msls_link_create' );
}

````

I'm sorry I don't have the exact error messages written down and I've rolled back everywhere now but I believe it was something along the lines that MslsOutput and MslsLink could not be found.

Let me know if you need further help debugging this.

**Comment by edwinbradford** [comment]
Thanks, I found the new site by accident and tried the exact same solution as you but it threw a PHP error for that line on my local server. Baffling that it worked for you and even more baffling that my solution worked on one server but not another when the two installations are mirror copies.

If I have time I might try installing the same version of PHP on my local server that my webhost is running but I'm hoping someone will find a bug and fix it before I get to that stage.

**Comment by edwinbradford** [comment]
Thank you :)

My server copy of phpMyAdmin is reporting 7.2.7 so I followed [this guide](https://www.inmotionhosting.com/support/edu/cpanel/getting-started-cpanel/how-to-view-your-php-version-in-cpanel) that checks using cPanel and it reported PHP version 5.6.38.

I will contact my hosting provider and see if I can upgrade the PHP version.

What is the minimum version of PHP you recommend?

**Comment by lloc** [comment]
OK, [here also the link to the PHP documentation](http://php.net/manual/en/language.types.array.php) where I copied the following statement:

> As of PHP 5.4 you can also use the short array syntax, which replaces array() with [].

**Comment by edwinbradford** [comment]
Solved... it was the PHP version as you suggested.

Thanks for the great help.
