### ISSUE TITLE
Remove msls_head hook doesn't work anymore

### ISSUE THREAD

**Issue by joeljv91** [lloc/Multisite-Language-Switcher#129]
Hi,

On the documentation it shows this code to remove hreflangs and this doesn't work with the new version of this plugin.

`remove_action( 'wp_head', 'msls_head' );`

Any ideas?

Wordpress Version: 5.1.0
MSLS Version: 2.3.0

Thanks

**Comment by lloc** [comment]
The callback is now in a class 

`add_action( 'wp_head', [ $obj, 'print_alternate_links' ] );`

I'm going to update the documentation. Good catch!

**Comment by joeljv91** [comment]
How can we remove this action from our functions.php?

**Comment by lloc** [comment]
This should work `remove_action( 'wp_head', [ lloc\Msls\MslsPlugin::class, 'print_alternate_links' ] );`

**Comment by joeljv91** [comment]
Same problem with this code, the hreflangs generated by multisite language switcher aren't removed.I think we need the same instance of the object to remove this from actions.

**Comment by K3CK** [comment]
I can confirm that the suggested solution is not working. 

For now as a quick & dirty solution I commented line 52 in MslsPlugin.php to prevent the hreflang output.

**Comment by lloc** [comment]
Please, send a pull request if you have a solution. There should better be an option in the dashboard if the filter is not the right solution.

**Comment by joeljv91** [comment]
This doesn't work for me:
`remove_action( 'wp_head', [ lloc\Msls\MslsPlugin::class, 'print_alternate_links' ] );`

But this works well:
`remove_action( 'wp_head', [ lloc\Msls\MslsPlugin::class, 'print_alternate_links' ] );`
