### ISSUE TITLE
Problem mit Woocommerce-Kategorien

### ISSUE THREAD

**Issue by Multiplecs** [lloc/Multisite-Language-Switcher#133]
Hallo Dennis,

folgendes Problem taucht mit dem Multisite-Language-Switcher in Verbindung mit Woocoomerce auf:

In Woocommerce können ja Kategorien angelegt werden. Hier können auch Bilder für die jeweilige Kategorie hinterlegt werden. Im Normalzustand können diese Kategorien in der Reihenfolge im Backend frei gereiht werden. Durch Drag and Drop über den Drei-Linien-Button kann die Kategorie einfach von einer Position auf die andere gezogen werden.

Sobald der Multisite-Language-Switcher aktiviert wird ist dies nicht mehr möglich. Wenn man versucht eine Kategorie zu verschieben springt sie beim Loslassen immer auf die vorherige Position zurück. Somit ist keine freie Anordnung der Kategorien mehr möglich.
Weiters verschwinden auch die Bilder der Kategorien in der Spalte Bild. Die Spalte selbst ist aber noch sichtbar (aber ohne Bilder).

Es sind jeweils die neuesten Versionen installiert. Wordpress läuft unter 5.2.2

Andere Plugins kann ich ausschließen da ich bereits alle anderen Plugins deaktiviert habe.

Vielen Dank für deine Hilfe.

Liebe Grüße
Christian

**Comment by lloc** [comment]
Ist das eventuell die Loesung? https://github.com/lloc/Multisite-Language-Switcher/issues/118

**Comment by hatsumatsu** [comment]
@lloc Giving the `manage_{$taxonomy}_custom_column` action a low priority (like `-100`) seems to fix this issue, no idea why...

https://github.com/lloc/Multisite-Language-Switcher/blob/cb5b43332425d1956e54340f70ef08e634acedcd/includes/MslsCustomColumnTaxonomy.php#L34

**Comment by Multiplecs** [comment]
Hallo Martin,

 

sorry vielmals für die späte Rückmeldung. Das E-Mail ist irgendwie untergegangen.

 

Vielen Dank für die Info. Funktioniert!

Dankeschön.

 

Wird dies beim nächsten Update von euch schon beachtet und aktualisiert?

 

 

Liebe Grüße

Christian

 

Multiplecs e. U.

Christian Schauperl

Fahrenbachstraße 18

A-8451 Heimschuh

 

T +43 650 8620999

E  <mailto:christian.schauperl@multiplecs.at> christian.schauperl@multiplecs.at

 <http://www.multiplecs.at/> www.multiplecs.at





Diese Nachricht und der Inhalt derselben ist ausschließlich für den genannten Adressaten bestimmt und kann vertrauliche oder auf andere Art von der Veröffentlichung ausgeschlossene Informationen beinhalten. Wenn Sie nicht der Adressat oder ein bevollmächtigter Vertreter des Adressaten sind, sind sie nicht berechtigt, diese Nachricht, die angeschlossenen Dateien und sonst irgendeinen Teil davon zu lesen, zu drucken, zu behalten, zu kopieren, weiterzugeben oder in sonst irgendeiner Form zu speichern oder wiederzugeben. Sollten Sie daher diese Nachricht irrtümlich erhalten haben, so verständigen Sie uns umgehend per e-mail oder Telefon und vernichten und löschen Sie alle Kopien dieser Nachricht.

Sämtliche übermittelte Konzepte, Entwürfe, Scribbles, Fotos, Illustrationen und Texte unterliegen dem Copyright und dürfen nur mit ausdrücklicher Genehmigung von Multiplecs e. U. veröffentlicht und verwendet werden.

 

UID-Nr.: ATU 64 210 767

Firmenbuchnr.: FN 407402x

 <https://www.multiplecs.at/fileadmin/multiplecs/dateien/agbs_multiplecs_april_2018_v1.2.pdf> Unsere Allgemeinen Geschäftsbedingungen

 <https://www.multiplecs.at/datenschutz/> Unsere Datenschutzrichtlinien

 

Von: Martin Wecke <notifications@github.com> 
Gesendet: Freitag, 3. Jänner 2020 11:21
An: lloc/Multisite-Language-Switcher <Multisite-Language-Switcher@noreply.github.com>
Cc: Multiplecs e. U. <christian.schauperl@multiplecs.at>; Author <author@noreply.github.com>
Betreff: Re: [lloc/Multisite-Language-Switcher] Problem mit Woocommerce-Kategorien (#133)

 

@lloc <https://github.com/lloc>  Giving the manage_{$taxonomy}_custom_column action a low priority (like -100) seems to fix this issue, no idea why...

https://github.com/lloc/Multisite-Language-Switcher/blob/cb5b43332425d1956e54340f70ef08e634acedcd/includes/MslsCustomColumnTaxonomy.php#L34
