### ISSUE TITLE
[PR] UI refresh

### ISSUE THREAD

**Issue by hatsumatsu** [lloc/Multisite-Language-Switcher#136]
Would you be interested in a PR that brings the UI closer to WP core and makes it hiDPI-ready by switching to SVG flags and using [WP Dashicons](https://developer.wordpress.org/resource/dashicons/#networking) for the icons?

Looks something like this:

![Screenshot 2019-11-22 at 11 33 18](https://user-images.githubusercontent.com/3452400/70034995-628d2280-15b2-11ea-8280-7f4ca6950393.png)

**Comment by lloc** [comment]
Yes, that would be very interesting indeed!

**Comment by hatsumatsu** [comment]
@lloc Cool! Only thing is that I get PHP errors when I build the current master branch. Is there a branch of the latest release / stable version I could work with?

**Comment by hatsumatsu** [comment]
To be more specific: Cloning the master branch and running `composer install --no-dev` I get these warnings when activating the plugin.

(PHP 7.2.15)

`````

Warning: array_merge(): Argument #2 is not an array in /path/to/wordpress/wp-includes/widgets.php on line 589

{main}( )  .../plugins.php:0
require_once( '/path/to/wordpress/wp-admin/network/admin.php' )  .../plugins.php:11
require_once( '/path/to/wordpress/wp-admin/admin.php' )  .../admin.php:13
require_once( '/path/to/wordpress/wp-load.php' )  .../admin.php:34
require_once( '/path/to/wordpress/wp-config.php' )  .../wp-load.php:37
require_once( '/path/to/wordpress/wp-settings.php' )  .../wp-config.php:100
do_action( )  .../wp-settings.php:523
WP_Hook->do_action( )  .../plugin.php:478
WP_Hook->apply_filters( )  .../class-wp-hook.php:312
wp_widgets_init( )  .../class-wp-hook.php:288
do_action( )  .../widgets.php:1765
WP_Hook->do_action( )  .../plugin.php:478
WP_Hook->apply_filters( )  .../class-wp-hook.php:312
WP_Widget_Factory->_register_widgets( )  .../class-wp-hook.php:288
lloc\Msls\MslsWidget->_register( )  .../class-wp-widget-factory.php:112
lloc\Msls\MslsWidget->_register_one( )  .../class-wp-widget.php:260
_register_widget_update_callback( )  .../class-wp-widget.php:551
array_merge ( )  .../widgets.php:589

`````

**Comment by lloc** [comment]
Ok, thanks ... I just pushed a fix to the master-branch. Seems there is no option to not to use the parent-constructor in a custom widget...

**Comment by hatsumatsu** [comment]
Just tested this and now I get this error on post.php / post-new.php:
``````
Fatal error: Uncaught Error: Using $this when not in object context in /Users/hatsumatsu/Sites/multilanguage.com/wp-content/plugins/Multisite-Language-Switcher/includes/MslsMetaBox.php on line 126
``````

**Comment by lloc** [comment]
I fixed this right now. Thanks for finding this!

**Comment by hatsumatsu** [comment]
@lloc Thanks for merging this into master! Looking forward to seeing this in the next release.
