### ISSUE TITLE
Problem with import content from translation

### ISSUE THREAD

**Issue by grapix** [lloc/Multisite-Language-Switcher#142]
**Describe the bug**
When you have more than one translation for a post, the content import function is only working for the last language. The metabox shows all translation buttons, but on click the thickbox contains nothing. By clicking on the last button, the thickbox is filled with content/options.

**To Reproduce**
1. Install fresh Wordpress Multisite
2. Setup two more sites
3. Install MSLS 2.3.0
4. "Activate the content import functionality" under settings for one or all sites
5. Open/create a page in one of your three blogs and connect it with translations
6. The metabox "Import content" should show two buttons – click the first

**Expected behaviour**
The thickbox should always contain options for duplicating content.

**Screenshots**
![1_2asdtgerdh](https://user-images.githubusercontent.com/6536415/71977284-aeb62d00-3218-11ea-839e-d60d8960ea87.png)
![1_32gsdf](https://user-images.githubusercontent.com/6536415/71977285-aeb62d00-3218-11ea-825b-5519dec23a82.png)
![1_sedgwerh](https://user-images.githubusercontent.com/6536415/71977286-aeb62d00-3218-11ea-9381-a5ea5648cd40.png)

**Comment by lloc** [comment]
@lucatume Can you help here?

**Comment by lucatume** [comment]
@lloc I can take a look at this, I'm assigning this to me to look into this as soon as I have time.
Thanks @grapix for reporting the issue and providing the details.

**Comment by lucatume** [comment]
@lloc I cannot assign the issue to my (I guess I'm not authorized to); could you please assign this to me?

**Comment by chegor** [comment]
hmmm, I still able to reproduce this issue in 2.9.5
