### ISSUE TITLE
[Enhancement][UX] Drop flag icons in favour of text based labels

### ISSUE THREAD

**Issue by hatsumatsu** [lloc/Multisite-Language-Switcher#152]
Using the plugin in a recent project I came across the general problem of representing languages via flag icons. The site contained an arabic language version in which the language code `AR` became represented by an Argentinian flag in the backend. In this particular case the language can not easily represented by a nation's flag. Issue #144 seems related to this issue.

Doing a little research I found this old post on stackoverflow: [How to graphically represent a language](https://ux.stackexchange.com/questions/2472/how-to-graphically-represent-a-language).

> "Conclusion considering the answers: Do not use a flag to represent a language. "

Which brings me to the suggestion of dropping flag icons in the backend alltogether and introducing text based labels. This could look like this:

![02](https://user-images.githubusercontent.com/3452400/83424443-b0cd9200-a42c-11ea-99b1-d56a09136b17.png)
![01](https://user-images.githubusercontent.com/3452400/83424447-b1febf00-a42c-11ea-8374-5edd6a735835.png)

PLUS: These badges could also be used in the admin bar's site list.

I can draft a PR for this if you like, it could  also be an option in the settings.

**Comment by hatsumatsu** [comment]
I stitched something together in #155 ...

<img width="1224" alt="Screenshot 2020-06-30 at 11 16 46" src="https://user-images.githubusercontent.com/3452400/86109529-c3d39080-bac4-11ea-887b-004fcbf71deb.png">

**Comment by lloc** [comment]
I'm going to close this since we have this feature. I wouldn't drop the flags entirely since I know some use cases where the websites represent markets.
