### ISSUE TITLE
Multisite network sites the user don't have access to gets listed to the admin bar

### ISSUE THREAD

**Issue by ruttoa** [lloc/Multisite-Language-Switcher#156]
**Describe the bug**
I have a multisite setup with ~20 sites. If I log in with username that has access to only one site for example, all the rest of the sites gets listed to the admin bar clogging it.

**To Reproduce**
1. Use plugin version 2.4.4 or newer
2. On multisite network with multiple sites log in with user that has access to only one site
3. See all the rest of the sites in the admin bar

**Expected behaviour**
These links / list items shoud not exist.

**Screenshots**
<img width="760" alt="Screen shot 2020-7-1 kello 17 01 18" src="https://user-images.githubusercontent.com/4192143/86253025-a2ee6680-bbbc-11ea-8beb-e00232246a83.png">

**Environment (please complete the following information):**
- OS: MacOS 10.15.5
- Browser: Chrome 84
- PHP Version 7.4.7
- Plugin Version: 2.4.6

**Additional context**
With version 2.4.3 this bug don't exist.

**Comment by lloc** [comment]
Interesting! Thanks for that catch...
