### ISSUE TITLE
Feature Request - Switcher on admin edit view

### ISSUE THREAD

**Issue by Idealien** [lloc/Multisite-Language-Switcher#157]
**Describe the feature**
This feature would add a link to the switcher panel for cases where a translation has already been identified.

On the posts/pages/CPT list view screen, the plugin provides an easy way to add/edit a translation. If you were making a typo correction or addition to an existing translation, that makes it "one click" easy to work between languages. However if you are already on the post/page/CPT edit view screen, there is no way to directly navigate between languages from the Switcher panel. 

The closest UI pattern to get there would be:
- 3 clicks - Click view current post, use front-end language switch, click edit post from admin bar.
- 3+ clicks - Use multisite menu to select the subsite dashboard of translation, select posts list view and edit translation post.

**Expected behaviour**
That accessing the edit view for a translated post/page/CPT translation is one-click away from the edit screen (as is already the case for the post list view).

**Screenshots**
![Mockup](https://user-images.githubusercontent.com/4549984/92334803-3893ef80-f05f-11ea-956a-94ed3258df85.png)

**Comment by lloc** [comment]
It is not so evident but the flags are linked to the post. Sure, it could be helpful to add also a text link.

**Comment by Idealien** [comment]
TIL 😅 

I'll close the request since that is already providing the feature desired with less use of UI real estate. Thanks!
Perhaps an update to http://msls.co/user-docs/editing-association-contents.html#status-of-connections would help others along their path (what should have been) obvious.
