### ISSUE TITLE
Changing Admin language settings disassociates translated posts

### ISSUE THREAD

**Issue by edwinbradford** [lloc/Multisite-Language-Switcher#167]
Please close this issue if it is expected behaviour but I seem to recall previously the MSLS Blog Language setting changes the **_Admin_** language and should not affect the association of translations unless the settings have changed.

1. In each blog (I have two) change MSLS Settings > Blog Language to the language of the blog.
2. Create a post and a translation from either blog (I use subfolders not domains).
3. In one of the blogs change MSLS Settings > Blog Language to the language of the other blog.
4. View any Post and its translation is no longer found.

**Expected behaviour**
I believe this setting is meant to---or used to---change the admin language only. Currently it appears that the Admin language must be set to the language of the blog else posts become disassociated. Fortunately for me I can read the blog language for the most part and luckily setting the Admin language to the language of the blog restores the post translations so I can work around the issue. 

WordPress 5.6.1
Multisite Language Switcher 2.4.10
PHP 8.0.0
MariaDB 10.4.17

**Comment by lloc** [comment]
Lets's say it is not optimal but the plugin uses the region-code and not the blog_id as you probably did expect.

**Comment by edwinbradford** [comment]
In that case I'll mark this issue as closed, it appears to be the expected behaviour and I really just wanted to make sure you were aware of the behaviour and it is correct.

I didn't mention it but thanks for such great software that has been working reliably without any issues for several years, I used to use WPML but migrated to MSLS and actually it's been a better experience for me.

**Comment by lloc** [comment]
Tanks for your kind words!
