### ISSUE TITLE
Wrong product slug since last update

### ISSUE THREAD

**Issue by ip-web** [lloc/Multisite-Language-Switcher#175]
Hello,
Since last update the product slug are the wrong one for each site, I've a french an english version of the site where the permalink are like this, for FR : mysite/**produit**/mon-produit 
EN : en.mysite/**product**/my-product

but when i visit wichever version of the site it's using the other one product slug to make the link like this on the english version it will show mysite/**product**/mon-produit instead of mysite/**produit**/mon-produit
in the settings of the MSLS I see that the product slug for the french is produit and for the english product but I can't change them the fields are in read only mode
live example here : https://naturacheval.fr/produit/activ-recup-equin-poudre/

**Comment by lloc** [comment]
I'm going to close this in favor of https://github.com/lloc/Multisite-Language-Switcher/issues/399.
