### ISSUE TITLE
MslsCustomColumn/MslsAdminIcon fatal error

### ISSUE THREAD

**Issue by nelgmo** [lloc/Multisite-Language-Switcher#192]
**Describe the bug**
I receive a fatal error after last update. 

`PHP message: PHP Fatal error: Uncaught TypeError: lloc\Msls\MslsAdminIcon::__construct(): Argument #1 ($type) must be of type string, null given, called in /www/hidden/public/wp-content/plugins/multisite-language-switcher/includes/MslsCustomColumn.php on line 54 and defined in /www/hidden/public/wp-content/plugins/multisite-language-switcher/includes/MslsAdminIcon.php:76
Stack trace:
#0 /www/hidden/public/wp-content/plugins/multisite-language-switcher/includes/MslsCustomColumn.php(54): lloc\Msls\MslsAdminIcon->__construct(NULL)
#1 /www/hidden/public/wp-includes/class-wp-hook.php(307): lloc\Msls\MslsCustomColumn->th(Array)
#2 /www/hidden/public/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array)
#3 /www/hidden/public/wp-admin/includes/class-wp-posts-list-table.php(739): apply_filters('manage_producti...', Array)
#4 /www/hidden/public/wp-includes/class-wp-hook.php(307): WP_Posts_List_Table->get_columns(Array)`

I have temporarily solved it by modifying row below. Setting i to `$icon = new MslsAdminIcon( '' );`
https://github.com/lloc/Multisite-Language-Switcher/blob/master/includes/MslsCustomColumn.php#L54

**To Reproduce**
Can't say really since it is not my code. But some custom initiation of the plugin is done in the code.
`$blog     = lloc\Msls\MslsBlogCollection::instance()->get_current_blog();`

**Expected behaviour**
No fatal error or for it to fail more gracefully.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Kinsta
 - Browser N/A
 - PHP Version 8.0
- Plugin Version 2.2.

**Additional context**

**Comment by lloc** [comment]
Version 2.5.7 addresses the problem in environments with PHP 8 installed.

Thanks a lot!
