### ISSUE TITLE
Missing MSLS Dropdown on Taxonomy Edit Screen term.php

### ISSUE THREAD

**Issue by dollseb** [lloc/Multisite-Language-Switcher#249]
A customer asked why he can't change the assignment of a translation for a custom taxonomy tag afterwards like on a regular page or a post. By this I mean a page like this: term.php?taxonomy=nameoftax&tag_ID=XX

Then in your source code I saw that there is no action that registers the dropdown there and I just added this code after line 74:

includes/MslsPlugin.php
`add_action( 'load-term.php', [ MslsPostTag::class, 'init' ] );`

As far as I can see, it's enough to add this line so when editing a taxonomy entry the corresponding term in another language can be selected afterwards. Was the entry not set for a specific reason? Does this cause any problems? 

Thanks and many greetings!

**Comment by lloc** [comment]
Great catch! Would you mind opening a pull request?

**Comment by dollseb** [comment]
I do. Is tomorrow fast enough?

**Comment by lloc** [comment]
Sure! Take your time. ;-)

**Comment by lloc** [comment]
I'm going to close it. The patch has been applied.
