### ISSUE TITLE
Directly fill in the Post ID or search to find the corresponding translated article

### ISSUE THREAD

**Issue by jevona** [lloc/Multisite-Language-Switcher#297]
When there are a huge number of articles, it is difficult to find corresponding translated articles. I hope to be able to search for corresponding articles in other languages, or to directly fill in the Post-ID. Sorry I don't speak English, I hope I can express myself clearly.

Supplement: You can search for translation items in alphabetical order in English, but it is very difficult to search in alphabetical order for non-English languages.

**Comment by jevona** [comment]
经过努力学习PHP代码基础知识，终于自己能修改这个问题（Sorry, I don't speak English, so I can only answer the questions I asked before in my native language）
**第一步：找到/include/MslsMetaBox.php文件，注释掉第208行以下代码：**
`$selects .= sprintf(
	'<select name="msls_input_%s"><option value="0"></option>%s</select>',
	$language,
	$this->render_options( $type, $mydata->$language )
);`

**第二步：然后再替换成我写的以下代码：**
`$nut_id = $mydata->$language;
$nut_title = isset($nut_id)?get_the_title( $mydata->$language ):null;
$selects .= sprintf(
	'<input type="text" name="msls_input_%s" size="1" placeholder="%s">&nbsp;<span>%s</span>',
	$language,
	$nut_id,
	$nut_title
);`

这样你只需要在input里面填写相对应的post id就可以了，不需要在select选择框里寻找对应的翻译文章。

最后感谢插件作者提供的多站点语言切换插件！这是一个相对冷门的WordPress插件，但我希望有更多人使用这个插件。

**Comment by lloc** [comment]
Thanks for this interesting insights. I will look into it!

**Comment by lloc** [comment]
Version 2.9.1 includes this feature
