### ISSUE TITLE
Autocomplete search input broken in latest version

### ISSUE THREAD

**Issue by hatsumatsu** [lloc/Multisite-Language-Switcher#352]
**Describe the bug**
After the latest updates, the *experimental* autocomplete search widget to connect posts is broken. When typing in the input field,  no posts are shown. 

**To Reproduce**
1. Enable the *experimental autocomplete inputs* feature
2. Edit a post
3. Search for a post title in the connected sites
4. No posts are returned

**Environment (please complete the following information):**
- PHP Version 8.2
- Plugin Version 2.8.1

**Fix**
After some debugging it seems that in the `suggest()` method, query vars are retrieved from the GET object, though the autocomplete request method ist POST.

https://github.com/lloc/Multisite-Language-Switcher/blob/5e89e49637cfbf8e7e97a50b7fef51c28ed78229/includes/MslsMetaBox.php#L20

Switching from `INPUT_GET` to `INPUT_POST` in this method fixes the bug.

**Comment by lloc** [comment]
It looks good to me. Please, send a PR.

**Comment by hatsumatsu** [comment]
> It looks good to me. Please, send a PR.

https://github.com/lloc/Multisite-Language-Switcher/pull/353 here we go
