### ISSUE TITLE
Import content #blank frame

### ISSUE THREAD

**Issue by kurageart** [lloc/Multisite-Language-Switcher#360]
Import content button only opens a blank frame, nothing happens

Using the standard edit interface.

A window should open where should be possible select what to import, and visualize progress

![Screenshot_20240806_233338](https://github.com/user-attachments/assets/528cc6a5-ca70-4c4a-9a77-840fdc670291)

**Environment (please complete the following information):**
 - OS: [endavouros linux]
 - Browser [firefox, brave]
 - PHP Version [e.g. 8.2]
- Plugin Version [latest]

**Additional context**
I'm using cloudpanel for hosting the wp site. It uses nginx instead of apache. Maybe some nginx custom rules needs to be written to allow this?

**Comment by lloc** [comment]
OK I will test this!

**Comment by lloc** [comment]
Bug confirmed!

**Comment by lloc** [comment]
The master branch has a fix for the issue. I just test it and roll it out later!
