### ISSUE TITLE
Can't connect / translate WooCommerce product attributes taxonomy terms

### ISSUE THREAD

**Issue by dademaru** [lloc/Multisite-Language-Switcher#71]
I'm reporting the issue opened here: https://wordpress.org/support/topic/cant-connect-translate-custom-taxonomy-terms

Using WooCommerce on Multisite I can't translate product attributes, and their corresponding terms.
When creating or editing a new term, the Multisite Language Switcher select is empty - can't find anything in the other language.
When I click on the “add translation” icon, I get an error page with “invalid taxonomy” message.
Whilst the attribute itself (product_attributes) hasn't at all the possibility of adding / connecting the translation.

**Comment by lloc** [comment]
I'm going to close this in favour of the issue [#67](https://github.com/lloc/Multisite-Language-Switcher/issues/67)
