### ISSUE TITLE
Alternate english languages show same tags

### ISSUE THREAD

**Issue by nathanlampe** [lloc/Multisite-Language-Switcher#75]
I have a blog that uses en-US and en-GB but the generated language header tags just show "en" which doesn't tell google there is actually an alternative.

link rel="alternate" hreflang="en" href="example.com" 
link rel="alternate" hreflang="en" href="example.com" 

when it should be something similar to:
link rel="alternate" hreflang="en-US" href="example.com"
link rel="alternate" hreflang="en-GB" href="example.com" 

I know this is an edge case and that most people don't change too much or even use an alternative for GB english.

**Comment by AtulDabhi** [comment]
Instead of en-gb, I got en_GB as hreflang value. I used the same code as above.
Any help?
