### ISSUE TITLE
get_bloginfo('language') returns the current site language when using switch_to_blog()

### ISSUE THREAD

**Issue by wujekbogdan** [lloc/Multisite-Language-Switcher#78]
```
foreach($sites as $site) {

    $blog_id = intval($site['blog_id']);
    switch_to_blog($blog_id);
    var_dump(get_bloginfo('language')); // Returns always the language of initial site
    restore_current_blog();

}
```

get_bloginfo('language') always returns the initial site language (like switch_to_blog() was never used), when other get_bloginfo() parameters work like expected . For example get_bloginfo('name') returns correct blog name.

As a workaround I can use get_option('WPLANG') but still it looks like a bug that should be fixed.

**Comment by lloc** [comment]
You don't use no function from Multisite Language Switcher at all in your example. WordPress has a get_locale()-function, the plugin gives you this:

    $blog = MslsBlogCollection::instance()->get_current_blog();
    $language = $blog->get_language();
