### ISSUE TITLE
bloginfo('language') used in wp admin returns admin language instead of blog language.

### ISSUE THREAD

**Issue by wujekbogdan** [lloc/Multisite-Language-Switcher#79]
I use a different language for blog and different for wp admin. Blog language is set to spanish, admin language is set to english. bloginfo('language') used in the WP admin returns admin language (i mean english). I expected it to return the blog language - spanish. For me it looks like a bug.

**Comment by lloc** [comment]
That is no bug because WPLANG is intentionally set to 'English' in this case. Use the preferred way if you need the language of the blog:

    $blog     = MslsBlogCollection::instance()->get_current_blog();
    $language = $blog->get_language();
