### ISSUE TITLE
Metabox filter issue using wp plugin directory 

### ISSUE THREAD

**Issue by starise** [lloc/Multisite-Language-Switcher#81]
Using wpackagist (it's a mirror for wordpress plugin directory) to get this plugin (">=1.0.4") via composer, the filter 'msls_meta_box_render_select_hierarchical' (#64) doesn't work at all. To work with it i had to sync my app with the master repository on github.

Not sure if it's willed, but looks like a mistake.

**Comment by lloc** [comment]
Version 1.0.5 will be the next version. Here at GitHub is my working-copy...  ;)

**Comment by starise** [comment]
:+1:
