### ISSUE TITLE
Flag icons disapering sometimes (wp 4.1.1)

### ISSUE THREAD

**Issue by ricemann** [lloc/Multisite-Language-Switcher#82]
I have made af fresh multisite install. With two sites: 
- domæne/da - (danish admin interface - pages in danish)
- domæne/en - (us english admin interface pages in english)

To reproduce the bug:
1) Navigate to one of the sites
2) Use switch to change
3) Switch between the two many times - and the flags are gone all of a sudden.

To get the flags show again I can make a hard page refresh.

I think my setup is correct and it seames to work - but i cannot be sure??
If you can investigate if it is a bug and point me in the right direction I will gladly fork the project and make a pullrequest when done. But I have to be sure it really is a bug.

Thomas aka Ricemann

**Comment by lloc** [comment]
How do you place the switcher in your pages? Widget, code ... what theme do you use?

**Comment by ricemann** [comment]
I use a widget.

**Comment by lloc** [comment]
I'd like to see the website. Please post a link!

**Comment by ricemann** [comment]
Sorry I did't see you answer - actually I was on my company website http://riisolution.com - but I have just tested and It works like a charm. Maybe it was an issue on MAMP. I think you can close the ticket for now : )

**Comment by lloc** [comment]
After clicking a while I saw this message here: "Your access to this site has been limited" ... seems there is something installed that checks if your a re human or a bot.
