### ISSUE TITLE
Get corresponding page ID

### ISSUE THREAD

**Issue by sparrox** [lloc/Multisite-Language-Switcher#86]
Hello,

I have a configuration with 2 languages (FR and EN) and I want to get an EN page id with the FR page id. 

Is there a function that would help me to do that ?

**Comment by 2xAA** [comment]
@lloc Is there a way to do this? Hreflang isn't working as expected, I'd like to write a filter to fix this, or even a PR.

Thanks.

**Comment by lloc** [comment]
Sorry for responding late ... there is indeed a possibility. For the queried object:

`print_r( MslsOptions::create()->get_arr() );` 

But you can pass also an ID:

`print_r( MslsOptions::create()->get_arr( 1 ) );` 

This would output the stored data-structure of an object (probably a post in that case) with the ID 1.
