### ISSUE TITLE
Show language name instead of code

### ISSUE THREAD

**Issue by devanes** [lloc/Multisite-Language-Switcher#88]
When I use the mslsmenu plugin with descriptions or the translations hints, it shows the language codes (like en_GB), instead of their names (like English). The same happens in the admin ("Het Bronsvuur / en_GB | Het Bronsvuur / nl_NL"). Is there a way to fix this?
This is using a freshly installed version from the plugin directory.

**Comment by creativeer** [comment]
Hi Devanes,

maybe this can help your Question:
In the Settings of this Plugin you have a "Description" Field (in your native language, it can have another wording). What you write into it, comes as Title out. I have made the same and it was working (from en_GB i have written English - and now the Title says English).

**Comment by devanes** [comment]
Thanks a lot. That did the trick.

**Comment by lloc** [comment]
Thanks for helping out here :) ... there is also a website for this plugin: msls.co It's the branch "gh-pages" at GitHub if someone wants to help with the documentation... ;)
