### ISSUE TITLE
Unable to create Setup for New language

### ISSUE THREAD

**Issue by Rage-Rage** [lloc/Multisite-Language-Switcher#89]
I have a blog site in wordpress under the website. So the URL of my website would be "http://domain.com/blog". And when i try to create a new site setup for Chinese language the URL would be "http://doamin.com/blog/ch". 

But the URL for admin of the Chinese setup is automatically set to "http://domain.com/blog/ch/wp-admin" which does not exists. So i am unable to proceed further.

**Comment by lloc** [comment]
I cannot help here. A working multisite is a must for the switcher.
