### ISSUE TITLE
Add ability to add custom hreflang

### ISSUE THREAD

**Issue by christianesperar** [lloc/Multisite-Language-Switcher#91]
This field will override the default one if there is content

**Comment by lloc** [comment]
Could you please describe the use-case a little bit.

**Comment by christianesperar** [comment]
Our SEO team want us to have custom lang code like hk_HK or hk-HK. So one option and easy implimentation is to have an option on multisite language switcher to override it. I think the logic is when hreflang has value, override and do no other processing.

**Comment by lloc** [comment]
Ok, there is already a filter for this: https://github.com/lloc/Multisite-Language-Switcher/blob/master/MultisiteLanguageSwitcher.php#L252

So you can archive this easily like so:

    function my_msls_head_hreflang ( $language ) {
        return $language;
    }
    add_filter( 'msls_head_hreflang', 'my_msls_head_hreflang' );

**Comment by christianesperar** [comment]
Nice! Thanks!
