### ISSUE TITLE
Fatal error MslsOptionsPost::get_tax_query() in MslsOptionsTaxTerm.php

### ISSUE THREAD

**Issue by wallenium** [lloc/Multisite-Language-Switcher#98]
I am using code in  custom module, wich is extending the msls note-system (it is showing a flyover when an alternative language (browser language detection) is discovered. I am willing to publish it on github once i have the time, the code is not the cleanest, but it is working.

Since mid of december, the following error occures in the tag-pages:

```
Fatal error: Call to undefined method MslsOptionsPost::get_tax_query() in .../wp-content/plugins/multisite-language-switcher/includes/MslsOptionsTaxTerm.php on line 46
```

the code i am using is roughly:

```
$blogs = MslsBlogCollection::instance();
        $post  = new MslsOptionsPost($id);
        foreach ($blogs->get_filtered() as $blog) {
            if ($blog->userblog_id != $blogs->get_current_blog_id()) {
                $language   = $blog->get_language();
```

**Comment by wallenium** [comment]
any hint where to search?

**Comment by lloc** [comment]
Yes, I tried to understand  what the problem could be. In the second line you create a MslsOptionsPost-object explicitly. This type of object doesn't have a get_tax_query()-method ...

You can also use the factory:

`$post = MslsOptions::create( $id );`

**Comment by wallenium** [comment]
thx a lot. 
$post				= MslsOptions::create($id);

fixed the issue.

**Comment by lloc** [comment]
I will let this issue open until I checked if I should move the get_tax_query()-method.
