### ISSUE TITLE
After update to 4.4.1 the language switcher is missing

### ISSUE THREAD

**Issue by noetig** [lloc/Multisite-Language-Switcher#99]
I updated my multisite today to 4.4.1. After the language switcher that normally is on top of the page was missing. Checked the links in the pages and they seems right. Checked also the settings for the plugin but all settings are like before. Changes have no effect. Changed also the theme because I got there a update too. But nothing changed. Source code shows no Language Switcher Code.

**Comment by lloc** [comment]
How was the switcher integratef before you updated the theme? Widget? Code? Do you use a child theme?
